version: "3.9"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: "zookeeper"
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    container_name: "kafka"
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
  db:
    image: postgres
    container_name: postgreDB
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: 123
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"

  userservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: userservice
    ports:
      - "8081:8081"
    expose:
      - "8081"
    depends_on:
      - zookeeper
      - kafka
      - redis
      - db
